name: Deploy Pagamento to Hetzner VPS

on:
  push:
    branches:
      - main # O branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Conectado à VPS. Iniciando deploy do pagamento..."
          # Mude para o diretório de destino do pagamento
          cd /home/gerenciaGR/pagamento
          # Puxa as últimas alterações do GitHub
          git pull origin main
          # Comandos pós-deploy (ex: reinicie o serviço)
          # Exemplo: sudo systemctl restart pagamento_service
          echo "Deploy do pagamento concluído!"
	  pm2 restart all
	  echo "PM2 reiniciado"


